#!/bin/bash

# oracle: Start/Stop Oracle Database
#
# chkconfig: 345 90 10
# description: The Oracle Database is an Object-Relational Database Management System.
#
# processname: oracle
#
# Add it like this on RHEL5/6
# copy script to /etc/rc.d/init.d/oracle
# chmod 755 /etc/rc.d/init.d/oracle
# chkconfig --add oracle
# chkconfig oracle on


source /etc/rc.d/init.d/functions

LOCKFILE="/var/lock/subsys/oracle"
ORACLE_HOME="/opt/oracle/product/12.1/db"
ORACLE_USER="oracle"

case "${1}" in
'start')
    if [ -f "${LOCKFILE}" ]; then
        echo "${0}  already running"
        exit 1
    fi

    echo -n $"Starting Oracle Database:"
    su - ${ORACLE_USER} -c "${ORACLE_HOME}/bin/lsnrctl start"
    su - ${ORACLE_USER} -c "${ORACLE_HOME}/bin/dbstart ${ORACLE_HOME}"
      touch ${LOCKFILE}
    ;;
'stop')
    if [ ! -f "${LOCKFILE}" ]; then
        echo "${0} already stopping."
        exit 1
    fi
    echo -n $"Stopping Oracle Database:"
    su - ${ORACLE_USER} -c "${ORACLE_HOME}/bin/lsnrctl stop"
    su - ${ORACLE_USER} -c "${ORACLE_HOME}/bin/dbshut ${ORACLE_HOME}"
    rm -f ${LOCKFILE}
    ;;
'restart')
    ${0} stop
    ${0} start
    ;;
'status')
    if [ -f "${LOCKFILE}" ]; then
        echo "${0} started."
    else
        echo "${0} stopped."
    fi
    ;;
*)
    echo "Usage: $0 [start|stop|status]"
    exit 1
esac

exit 0
